theme = "catppuccin_mocha"

[editor]
# line-number = "relative"
cursorline = true
bufferline = "multiple"
true-color = true
completion-timeout = 5
idle-timeout = 100
completion-trigger-len = 1
popup-border = "all"
# end-of-line-diagnostics = "hint"

[editor.lsp]
display-messages = false
display-inlay-hints = false

[editor.indent-guides]
render = true
character = "│"     # or "▏", "┆", etc.
skip-levels = 1     # how many levels to skip

[editor.auto-save]
auto-save = true
after-delay.enable = true

# [editor.inline-diagnostics]
# cursor-line = "warning"

[keys.insert.j]
k = "normal_mode" # maps `jk` to exit insert mode

