[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
args = ["--function-arg-placeholders=0"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "python"
language-servers = ["pylsp"]
[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true
[language.formatter]
command = "ruff"
args = ["format", "-"]
formatter = { command = "ruff", args = ["format"] }
