#include "../include/sprite_data.h"

const Rectangle sprite_db[SPRITE_MAX] = {
    [SPRITE_EFFECT_PURPLE]   = {.x = 156, .y = 32, .width = 32, .height = 64},
    [SPRITE_EFFECT_YELLOW]   = {.x = 180, .y = 181, .width = 32, .height = 64},
    [SPRITE_ENEMY_A]         = {.x = 0, .y = 420, .width = 48, .height = 48},
    [SPRITE_ENEMY_B]         = {.x = 100, .y = 140, .width = 48, .height = 48},
    [SPRITE_ENEMY_C]         = {.x = 0, .y = 0, .width = 64, .height = 32},
    [SPRITE_ENEMY_D]         = {.x = 100, .y = 188, .width = 48, .height = 48},
    [SPRITE_ENEMY_E]         = {.x = 100, .y = 332, .width = 48, .height = 48},
    [SPRITE_ICON_CROSSLARGE] = {.x = 100, .y = 236, .width = 48, .height = 48},
    [SPRITE_ICON_CROSSSMALL] = {.x = 176, .y = 0, .width = 32, .height = 32},
    [SPRITE_ICON_EXCLAMATIONLARGE] = {.x      = 100,
                                      .y      = 284,
                                      .width  = 48,
                                      .height = 48},
    [SPRITE_ICON_EXCLAMATIONSMALL] = {.x      = 148,
                                      .y      = 309,
                                      .width  = 32,
                                      .height = 32},
    [SPRITE_ICON_PLUSLARGE] = {.x = 104, .y = 80, .width = 48, .height = 48},
    [SPRITE_ICON_PLUSSMALL] = {.x = 148, .y = 229, .width = 32, .height = 32},
    [SPRITE_METEOR_DETAILEDLARGE] = {.x      = 144,
                                     .y      = 428,
                                     .width  = 48,
                                     .height = 48},
    [SPRITE_METEOR_DETAILEDSMALL] = {.x      = 144,
                                     .y      = 476,
                                     .width  = 32,
                                     .height = 32},
    [SPRITE_METEOR_LARGE] = {.x = 144, .y = 380, .width = 48, .height = 48},
    [SPRITE_METEOR_SMALL] = {.x = 112, .y = 0, .width = 32, .height = 32},
    [SPRITE_METEOR_SQUAREDETAILEDLARGE] = {.x      = 108,
                                           .y      = 32,
                                           .width  = 48,
                                           .height = 48},
    [SPRITE_METEOR_SQUAREDETAILEDSMALL] = {.x      = 152,
                                           .y      = 96,
                                           .width  = 32,
                                           .height = 32},
    [SPRITE_METEOR_SQUARELARGE]         = {.x      = 52,
                                           .y      = 340,
                                           .width  = 48,
                                           .height = 48},
    [SPRITE_METEOR_SQUARESMALL] = {.x = 144, .y = 0, .width = 32, .height = 32},
    [SPRITE_SATELLITE_A]        = {.x = 0, .y = 148, .width = 52, .height = 44},
    [SPRITE_SATELLITE_B]        = {.x = 0, .y = 192, .width = 52, .height = 52},
    [SPRITE_SATELLITE_C]        = {.x = 0, .y = 332, .width = 52, .height = 36},
    [SPRITE_SATELLITE_D]        = {.x = 0, .y = 296, .width = 52, .height = 36},
    [SPRITE_SHIP_A]      = {.x = 52, .y = 388, .width = 32, .height = 24},
    [SPRITE_SHIP_B]      = {.x = 148, .y = 341, .width = 16, .height = 32},
    [SPRITE_SHIP_C]      = {.x = 48, .y = 468, .width = 48, .height = 32},
    [SPRITE_SHIP_D]      = {.x = 64, .y = 0, .width = 48, .height = 32},
    [SPRITE_SHIP_E]      = {.x = 96, .y = 436, .width = 48, .height = 48},
    [SPRITE_SHIP_F]      = {.x = 96, .y = 388, .width = 48, .height = 48},
    [SPRITE_SHIP_G]      = {.x = 60, .y = 32, .width = 48, .height = 48},
    [SPRITE_SHIP_H]      = {.x = 56, .y = 92, .width = 48, .height = 48},
    [SPRITE_SHIP_I]      = {.x = 148, .y = 261, .width = 32, .height = 48},
    [SPRITE_SHIP_J]      = {.x = 52, .y = 292, .width = 48, .height = 48},
    [SPRITE_SHIP_K]      = {.x = 148, .y = 181, .width = 32, .height = 48},
    [SPRITE_SHIP_L]      = {.x = 52, .y = 244, .width = 48, .height = 48},
    [SPRITE_SHIP_SIDESA] = {.x = 148, .y = 128, .width = 42, .height = 53},
    [SPRITE_SHIP_SIDESB] = {.x = 0, .y = 244, .width = 52, .height = 52},
    [SPRITE_SHIP_SIDESC] = {.x = 0, .y = 368, .width = 52, .height = 52},
    [SPRITE_SHIP_SIDESD] = {.x = 0, .y = 468, .width = 48, .height = 32},
    [SPRITE_STAR_LARGE]  = {.x = 52, .y = 196, .width = 48, .height = 48},
    [SPRITE_STAR_MEDIUM] = {.x = 52, .y = 148, .width = 48, .height = 48},
    [SPRITE_STAR_SMALL]  = {.x = 96, .y = 484, .width = 16, .height = 16},
    [SPRITE_STAR_TINY]   = {.x = 112, .y = 484, .width = 16, .height = 16},
    [SPRITE_STATION_A]   = {.x = 48, .y = 420, .width = 48, .height = 48},
    [SPRITE_STATION_B]   = {.x = 0, .y = 92, .width = 56, .height = 56},
    [SPRITE_STATION_C]   = {.x = 0, .y = 32, .width = 60, .height = 60},
};
