#ifndef SPRITE_DATA_H
#define SPRITE_DATA_H

#include <raylib.h>

typedef enum SpriteData {
    SPRITE_EFFECT_PURPLE,
    SPRITE_EFFECT_YELLOW,
    SPRITE_ENEMY_A,
    SPRITE_ENEMY_B,
    SPRITE_ENEMY_C,
    SPRITE_ENEMY_D,
    SPRITE_ENEMY_E,
    SPRITE_ICON_CROSSLARGE,
    SPRITE_ICON_CROSSSMALL,
    SPRITE_ICON_EXCLAMATIONLARGE,
    SPRITE_ICON_EXCLAMATIONSMALL,
    SPRITE_ICON_PLUSLARGE,
    SPRITE_ICON_PLUSSMALL,
    SPRITE_METEOR_DETAILEDLARGE,
    SPRITE_METEOR_DETAILEDSMALL,
    SPRITE_METEOR_LARGE,
    SPRITE_METEOR_SMALL,
    SPRITE_METEOR_SQUAREDETAILEDLARGE,
    SPRITE_METEOR_SQUAREDETAILEDSMALL,
    SPRITE_METEOR_SQUARELARGE,
    SPRITE_METEOR_SQUARESMALL,
    SPRITE_SATELLITE_A,
    SPRITE_SATELLITE_B,
    SPRITE_SATELLITE_C,
    SPRITE_SATELLITE_D,
    SPRITE_SHIP_A,
    SPRITE_SHIP_B,
    SPRITE_SHIP_C,
    SPRITE_SHIP_D,
    SPRITE_SHIP_E,
    SPRITE_SHIP_F,
    SPRITE_SHIP_G,
    SPRITE_SHIP_H,
    SPRITE_SHIP_I,
    SPRITE_SHIP_J,
    SPRITE_SHIP_K,
    SPRITE_SHIP_L,
    SPRITE_SHIP_SIDESA,
    SPRITE_SHIP_SIDESB,
    SPRITE_SHIP_SIDESC,
    SPRITE_SHIP_SIDESD,
    SPRITE_STAR_LARGE,
    SPRITE_STAR_MEDIUM,
    SPRITE_STAR_SMALL,
    SPRITE_STAR_TINY,
    SPRITE_STATION_A,
    SPRITE_STATION_B,
    SPRITE_STATION_C,

    SPRITE_MAX

} SpriteData;

extern const Rectangle sprite_db[SPRITE_MAX];

#endif // SPRITE_DATA_H
