import pyray as p

SCREEN_WIDTH: int = 800
SCREEN_HEIGHT: int = 600
SCREEN_TITLE: str = "Space Survivors"
SCREEN_BACKGROUND: p.Color = p.RAYWHITE

MAP_SIZE: int = 2000

MAX_ENEMIES: int = 20
ENEMY_SPAWN_DISTANCE: float = 500.0
ENEMY_SPAWN_RATE: float = 5.0

MAX_BULLETS: int = 20
BULLET_SPAWN_RATE: float = 1.0
BULLET_MAX_LIFETIME = 2.0
