#include "animation_data.h"
#include "settings.h"
#include <assert.h>

const AnimationConfig warrior_animation_configs[WARRIOR_ANIMATION_MAX] = {
    [WARRIOR_ANIMATION_IDLE]             = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 0, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 1, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 2, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 3, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 4, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 5, 0, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
},
                                                          .count    = 6,
                                                          .duration = 0.60f,
                                                          .loops    = true}, // 10 FPS

    [WARRIOR_ANIMATION_RUN]              = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 1, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 8
},
                                                          .count    = 8,
                                                          .duration = 0.53f,
                                                          .loops    = true}, // ~15 FPS

    [WARRIOR_ANIMATION_TWO_COMBO_ATTACK] = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 2, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 8
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 9
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 3, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 10
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 11
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 12
    
},
                                                          .count    = 12,
                                                          .duration = 0.60f,
                                                          .loops    = false}, // 20 FPS

    [WARRIOR_ANIMATION_DEATH]            = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 4, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 8
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 9
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 5, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 10
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 11
},
                                                          .count    = 11,
                                                          .duration = 0.92f,
                                                          .loops    = false}, // 12 FPS

    [WARRIOR_ANIMATION_HURT]             = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
},
                                                          .count    = 4,
                                                          .duration = 0.27f,
                                                          .loops    = false}, // 15 FPS

    [WARRIOR_ANIMATION_JUMP]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 6, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    
}, .count = 3, .duration = 0.20f, .loops = false},

    [WARRIOR_ANIMATION_UPTO_FALL]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
}, .count = 2, .duration = 0.13f, .loops = false},

    [WARRIOR_ANIMATION_FALL] = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 7, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
},
                                              .count    = 3,
                                              .duration = 0.20f,
                                              .loops    = true}, // loop while falling

    [WARRIOR_ANIMATION_EDGE_GRAB]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 8, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
}, .count = 5, .duration = 0.33f, .loops = false},

    [WARRIOR_ANIMATION_EDGE_IDLE]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 9, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
}, .count = 6, .duration = 0.60f, .loops = true},

    [WARRIOR_ANIMATION_WALL_SLIDE]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
}, .count = 3, .duration = 0.30f, .loops = true},

    [WARRIOR_ANIMATION_CROUCH] = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 10, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
},
                                                .count    = 6,
                                                .duration = 0.40f,
                                                .loops    = false}, // transition into crouch

    [WARRIOR_ANIMATION_DASH]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 11, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
}, .count = 7, .duration = 0.35f, .loops = false},

    [WARRIOR_ANIMATION_DASH_ATTACK]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 12, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 13, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 8
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 9
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 10
}, .count = 10, .duration = 0.50f, .loops = false},

    [WARRIOR_ANIMATION_SLIDE]
    = {.frames = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 14, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
}, .count = 5, .duration = 0.30f, .loops = false},

    [WARRIOR_ANIMATION_LADDER_GRAB] = {.frames   = (Rectangle[]){
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 1
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 2
    {WARRIOR_SPRITE_WIDTH * 3, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 3
    {WARRIOR_SPRITE_WIDTH * 4, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 4
    {WARRIOR_SPRITE_WIDTH * 5, WARRIOR_SPRITE_HEIGHT * 15, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 5
    {WARRIOR_SPRITE_WIDTH * 0, WARRIOR_SPRITE_HEIGHT * 16, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 6
    {WARRIOR_SPRITE_WIDTH * 1, WARRIOR_SPRITE_HEIGHT * 16, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 7
    {WARRIOR_SPRITE_WIDTH * 2, WARRIOR_SPRITE_HEIGHT * 16, WARRIOR_SPRITE_WIDTH, WARRIOR_SPRITE_HEIGHT}, // 8
},
                                                     .count    = 8,
                                                     .duration = 0.67f,
                                                     .loops    = true}, // climbing
};
