#ifndef SETTINGS_H
#define SETTINGS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define MAP_SIZE 2000

#define WARRIOR_SPRITE_WIDTH 69
#define WARRIOR_SPRITE_HEIGHT 44

#endif // SETTINGS_H
