#include "texture_manager.h"

#include <assert.h>

void texture_manager_init(TextureManager *tm)
{
    assert(tm);

    tm->air_attack1_00       = LoadTexture("assets/air_attack1/0.png");
    tm->air_attack1_01       = LoadTexture("assets/air_attack1/1.png");
    tm->air_attack1_02       = LoadTexture("assets/air_attack1/2.png");
    tm->air_attack1_03       = LoadTexture("assets/air_attack1/3.png");
    tm->air_attack2_00       = LoadTexture("assets/air_attack2/0.png");
    tm->air_attack2_01       = LoadTexture("assets/air_attack2/1.png");
    tm->air_attack2_02       = LoadTexture("assets/air_attack2/2.png");
    tm->air_attack_3_end_00  = LoadTexture("assets/air_attack3_end/0.png");
    tm->air_attack_3_end_01  = LoadTexture("assets/air_attack3_end/1.png");
    tm->air_attack_3_end_02  = LoadTexture("assets/air_attack3_end/2.png");
    tm->air_attack3_loop_00  = LoadTexture("assets/air_attack3_loop/0.png");
    tm->air_attack3_loop_01  = LoadTexture("assets/air_attack3_loop/1.png");
    tm->air_attack3_ready_00 = LoadTexture("assets/air_attack3_ready/0.png");
    tm->attack1_00           = LoadTexture("assets/attack1/0.png");
    tm->attack1_01           = LoadTexture("assets/attack1/1.png");
    tm->attack1_02           = LoadTexture("assets/attack1/2.png");
    tm->attack1_03           = LoadTexture("assets/attack1/3.png");
    tm->attack1_04           = LoadTexture("assets/attack1/4.png");
    tm->attack2_00           = LoadTexture("assets/attack2/0.png");
    tm->attack2_01           = LoadTexture("assets/attack2/1.png");
    tm->attack2_02           = LoadTexture("assets/attack2/2.png");
    tm->attack2_03           = LoadTexture("assets/attack2/3.png");
    tm->attack2_04           = LoadTexture("assets/attack2/4.png");
    tm->attack2_05           = LoadTexture("assets/attack2/5.png");
    tm->attack3_00           = LoadTexture("assets/attack3/0.png");
    tm->attack3_01           = LoadTexture("assets/attack3/1.png");
    tm->attack3_02           = LoadTexture("assets/attack3/2.png");
    tm->attack3_03           = LoadTexture("assets/attack3/3.png");
    tm->attack3_04           = LoadTexture("assets/attack3/4.png");
    tm->attack3_05           = LoadTexture("assets/attack3/5.png");
    tm->bow_00               = LoadTexture("assets/bow/0.png");
    tm->bow_01               = LoadTexture("assets/bow/1.png");
    tm->bow_02               = LoadTexture("assets/bow/2.png");
    tm->bow_03               = LoadTexture("assets/bow/3.png");
    tm->bow_04               = LoadTexture("assets/bow/4.png");
    tm->bow_05               = LoadTexture("assets/bow/5.png");
    tm->bow_06               = LoadTexture("assets/bow/6.png");
    tm->bow_07               = LoadTexture("assets/bow/7.png");
    tm->bow_08               = LoadTexture("assets/bow/8.png");
    tm->bow_jump_00          = LoadTexture("assets/bow_jump/0.png");
    tm->bow_jump_01          = LoadTexture("assets/bow_jump/1.png");
    tm->bow_jump_02          = LoadTexture("assets/bow_jump/2.png");
    tm->bow_jump_03          = LoadTexture("assets/bow_jump/3.png");
    tm->bow_jump_04          = LoadTexture("assets/bow_jump/4.png");
    tm->bow_jump_05          = LoadTexture("assets/bow_jump/5.png");
    tm->cast_00              = LoadTexture("assets/cast/0.png");
    tm->cast_01              = LoadTexture("assets/cast/1.png");
    tm->cast_02              = LoadTexture("assets/cast/2.png");
    tm->cast_03              = LoadTexture("assets/cast/3.png");
    tm->cast_loop_00         = LoadTexture("assets/cast_loop/0.png");
    tm->cast_loop_01         = LoadTexture("assets/cast_loop/1.png");
    tm->cast_loop_02         = LoadTexture("assets/cast_loop/2.png");
    tm->cast_loop_03         = LoadTexture("assets/cast_loop/3.png");
    tm->corner_climb_00      = LoadTexture("assets/corner_climb/0.png");
    tm->corner_climb_01      = LoadTexture("assets/corner_climb/1.png");
    tm->corner_climb_02      = LoadTexture("assets/corner_climb/2.png");
    tm->corner_climb_03      = LoadTexture("assets/corner_climb/3.png");
    tm->corner_climb_04      = LoadTexture("assets/corner_climb/4.png");
    tm->corner_grab_00       = LoadTexture("assets/corner_grab/0.png");
    tm->corner_grab_01       = LoadTexture("assets/corner_grab/1.png");
    tm->corner_grab_02       = LoadTexture("assets/corner_grab/2.png");
    tm->corner_grab_03       = LoadTexture("assets/corner_grab/3.png");
    tm->corner_jump_00       = LoadTexture("assets/corner_jump/0.png");
    tm->corner_jump_01       = LoadTexture("assets/corner_jump/1.png");
    tm->crouch_00            = LoadTexture("assets/crouch/0.png");
    tm->crouch_01            = LoadTexture("assets/crouch/1.png");
    tm->crouch_02            = LoadTexture("assets/crouch/2.png");
    tm->crouch_03            = LoadTexture("assets/crouch/3.png");
    tm->crouch_walk_00       = LoadTexture("assets/crouch_walk/0.png");
    tm->crouch_walk_01       = LoadTexture("assets/crouch_walk/1.png");
    tm->crouch_walk_02       = LoadTexture("assets/crouch_walk/2.png");
    tm->crouch_walk_03       = LoadTexture("assets/crouch_walk/3.png");
    tm->crouch_walk_04       = LoadTexture("assets/crouch_walk/4.png");
    tm->crouch_walk_05       = LoadTexture("assets/crouch_walk/5.png");
    tm->die_00               = LoadTexture("assets/die/0.png");
    tm->die_01               = LoadTexture("assets/die/1.png");
    tm->die_02               = LoadTexture("assets/die/2.png");
    tm->die_03               = LoadTexture("assets/die/3.png");
    tm->die_04               = LoadTexture("assets/die/4.png");
    tm->die_05               = LoadTexture("assets/die/5.png");
    tm->die_06               = LoadTexture("assets/die/6.png");
    tm->drop_kick_00         = LoadTexture("assets/drop_kick/0.png");
    tm->drop_kick_01         = LoadTexture("assets/drop_kick/1.png");
    tm->drop_kick_02         = LoadTexture("assets/drop_kick/2.png");
    tm->drop_kick_03         = LoadTexture("assets/drop_kick/3.png");
    tm->fall_00              = LoadTexture("assets/fall/0.png");
    tm->fall_01              = LoadTexture("assets/fall/1.png");
    tm->get_up_00            = LoadTexture("assets/get_up/0.png");
    tm->get_up_01            = LoadTexture("assets/get_up/1.png");
    tm->get_up_02            = LoadTexture("assets/get_up/2.png");
    tm->get_up_03            = LoadTexture("assets/get_up/3.png");
    tm->get_up_04            = LoadTexture("assets/get_up/4.png");
    tm->get_up_05            = LoadTexture("assets/get_up/5.png");
    tm->get_up_06            = LoadTexture("assets/get_up/6.png");
    tm->hurt_00              = LoadTexture("assets/hurt/0.png");
    tm->hurt_01              = LoadTexture("assets/hurt/1.png");
    tm->hurt_02              = LoadTexture("assets/hurt/2.png");
    tm->idle_00              = LoadTexture("assets/idle/0.png");
    tm->idle_01              = LoadTexture("assets/idle/1.png");
    tm->idle_02              = LoadTexture("assets/idle/2.png");
    tm->idle_03              = LoadTexture("assets/idle/3.png");
    tm->idle2_00             = LoadTexture("assets/idle2/0.png");
    tm->idle2_01             = LoadTexture("assets/idle2/1.png");
    tm->idle2_02             = LoadTexture("assets/idle2/2.png");
    tm->idle2_03             = LoadTexture("assets/idle2/3.png");
    tm->items_00             = LoadTexture("assets/items/0.png");
    tm->items_01             = LoadTexture("assets/items/1.png");
    tm->items_02             = LoadTexture("assets/items/2.png");
    tm->jump_00              = LoadTexture("assets/jump/0.png");
    tm->jump_01              = LoadTexture("assets/jump/1.png");
    tm->jump_02              = LoadTexture("assets/jump/2.png");
    tm->jump_03              = LoadTexture("assets/jump/3.png");
    tm->kick_00              = LoadTexture("assets/kick/0.png");
    tm->kick_01              = LoadTexture("assets/kick/1.png");
    tm->kick_02              = LoadTexture("assets/kick/2.png");
    tm->kick_03              = LoadTexture("assets/kick/3.png");
    tm->kick_04              = LoadTexture("assets/kick/4.png");
    tm->kick_05              = LoadTexture("assets/kick/5.png");
    tm->kick_06              = LoadTexture("assets/kick/6.png");
    tm->kick_07              = LoadTexture("assets/kick/7.png");
    tm->knock_down_00        = LoadTexture("assets/knock_down/0.png");
    tm->knock_down_01        = LoadTexture("assets/knock_down/1.png");
    tm->knock_down_02        = LoadTexture("assets/knock_down/2.png");
    tm->knock_down_03        = LoadTexture("assets/knock_down/3.png");
    tm->knock_down_04        = LoadTexture("assets/knock_down/4.png");
    tm->knock_down_05        = LoadTexture("assets/knock_down/5.png");
    tm->knock_down_06        = LoadTexture("assets/knock_down/6.png");
    tm->ladder_climb_00      = LoadTexture("assets/ladder_climb/0.png");
    tm->ladder_climb_01      = LoadTexture("assets/ladder_climb/1.png");
    tm->ladder_climb_02      = LoadTexture("assets/ladder_climb/2.png");
    tm->ladder_climb_03      = LoadTexture("assets/ladder_climb/3.png");
    tm->punch_00             = LoadTexture("assets/punch/0.png");
    tm->punch_01             = LoadTexture("assets/punch/1.png");
    tm->punch_02             = LoadTexture("assets/punch/2.png");
    tm->punch_03             = LoadTexture("assets/punch/3.png");
    tm->punch_04             = LoadTexture("assets/punch/4.png");
    tm->punch_05             = LoadTexture("assets/punch/5.png");
    tm->punch_06             = LoadTexture("assets/punch/6.png");
    tm->punch_07             = LoadTexture("assets/punch/7.png");
    tm->punch_08             = LoadTexture("assets/punch/8.png");
    tm->punch_09             = LoadTexture("assets/punch/9.png");
    tm->punch_10             = LoadTexture("assets/punch/10.png");
    tm->punch_11             = LoadTexture("assets/punch/11.png");
    tm->punch_12             = LoadTexture("assets/punch/12.png");
    tm->run_00               = LoadTexture("assets/run/0.png");
    tm->run_01               = LoadTexture("assets/run/1.png");
    tm->run_02               = LoadTexture("assets/run/2.png");
    tm->run_03               = LoadTexture("assets/run/3.png");
    tm->run_04               = LoadTexture("assets/run/4.png");
    tm->run_05               = LoadTexture("assets/run/5.png");
    tm->run2_00              = LoadTexture("assets/run2/0.png");
    tm->run2_01              = LoadTexture("assets/run2/1.png");
    tm->run2_02              = LoadTexture("assets/run2/2.png");
    tm->run2_03              = LoadTexture("assets/run2/3.png");
    tm->run2_04              = LoadTexture("assets/run2/4.png");
    tm->run2_05              = LoadTexture("assets/run2/5.png");
    tm->run_punch_00         = LoadTexture("assets/run_punch/0.png");
    tm->run_punch_01         = LoadTexture("assets/run_punch/1.png");
    tm->run_punch_02         = LoadTexture("assets/run_punch/2.png");
    tm->run_punch_03         = LoadTexture("assets/run_punch/3.png");
    tm->run_punch_04         = LoadTexture("assets/run_punch/4.png");
    tm->run_punch_05         = LoadTexture("assets/run_punch/5.png");
    tm->run_punch_06         = LoadTexture("assets/run_punch/6.png");
    tm->slide_00             = LoadTexture("assets/slide/0.png");
    tm->slide_01             = LoadTexture("assets/slide/1.png");
    tm->somersault_00        = LoadTexture("assets/somersault/0.png");
    tm->somersault_01        = LoadTexture("assets/somersault/1.png");
    tm->somersault_02        = LoadTexture("assets/somersault/2.png");
    tm->somersault_03        = LoadTexture("assets/somersault/3.png");
    tm->stand_00             = LoadTexture("assets/stand/0.png");
    tm->stand_01             = LoadTexture("assets/stand/1.png");
    tm->stand_02             = LoadTexture("assets/stand/2.png");
    tm->sword_draw_00        = LoadTexture("assets/sword_draw/0.png");
    tm->sword_draw_01        = LoadTexture("assets/sword_draw/1.png");
    tm->sword_draw_02        = LoadTexture("assets/sword_draw/2.png");
    tm->sword_draw_03        = LoadTexture("assets/sword_draw/3.png");
    tm->sword_sheathe_00     = LoadTexture("assets/sword_sheathe/0.png");
    tm->sword_sheathe_01     = LoadTexture("assets/sword_sheathe/1.png");
    tm->sword_sheathe_02     = LoadTexture("assets/sword_sheathe/2.png");
    tm->sword_sheathe_03     = LoadTexture("assets/sword_sheathe/3.png");
    tm->walk_00              = LoadTexture("assets/walk/0.png");
    tm->walk_01              = LoadTexture("assets/walk/1.png");
    tm->walk_02              = LoadTexture("assets/walk/2.png");
    tm->walk_03              = LoadTexture("assets/walk/3.png");
    tm->walk_04              = LoadTexture("assets/walk/4.png");
    tm->walk_05              = LoadTexture("assets/walk/5.png");
    tm->wall_run_00          = LoadTexture("assets/wall_run/0.png");
    tm->wall_run_01          = LoadTexture("assets/wall_run/1.png");
    tm->wall_run_02          = LoadTexture("assets/wall_run/2.png");
    tm->wall_run_03          = LoadTexture("assets/wall_run/3.png");
    tm->wall_run_04          = LoadTexture("assets/wall_run/4.png");
    tm->wall_run_05          = LoadTexture("assets/wall_run/5.png");
    tm->wall_slide_00        = LoadTexture("assets/wall_slide/0.png");
    tm->wall_slide_01        = LoadTexture("assets/wall_slide/1.png");
}

void texture_manager_check(const TextureManager *tm)
{
    assert(tm);

    assert(IsTextureValid(tm->air_attack1_00));
    assert(IsTextureValid(tm->air_attack1_01));
    assert(IsTextureValid(tm->air_attack1_02));
    assert(IsTextureValid(tm->air_attack1_03));
    assert(IsTextureValid(tm->air_attack2_00));
    assert(IsTextureValid(tm->air_attack2_01));
    assert(IsTextureValid(tm->air_attack2_02));
    assert(IsTextureValid(tm->air_attack_3_end_00));
    assert(IsTextureValid(tm->air_attack_3_end_01));
    assert(IsTextureValid(tm->air_attack_3_end_02));
    assert(IsTextureValid(tm->air_attack3_loop_00));
    assert(IsTextureValid(tm->air_attack3_loop_01));
    assert(IsTextureValid(tm->air_attack3_ready_00));
    assert(IsTextureValid(tm->attack1_00));
    assert(IsTextureValid(tm->attack1_01));
    assert(IsTextureValid(tm->attack1_02));
    assert(IsTextureValid(tm->attack1_03));
    assert(IsTextureValid(tm->attack1_04));
    assert(IsTextureValid(tm->attack2_00));
    assert(IsTextureValid(tm->attack2_01));
    assert(IsTextureValid(tm->attack2_02));
    assert(IsTextureValid(tm->attack2_03));
    assert(IsTextureValid(tm->attack2_04));
    assert(IsTextureValid(tm->attack2_05));
    assert(IsTextureValid(tm->attack3_00));
    assert(IsTextureValid(tm->attack3_01));
    assert(IsTextureValid(tm->attack3_02));
    assert(IsTextureValid(tm->attack3_03));
    assert(IsTextureValid(tm->attack3_04));
    assert(IsTextureValid(tm->attack3_05));
    assert(IsTextureValid(tm->bow_00));
    assert(IsTextureValid(tm->bow_01));
    assert(IsTextureValid(tm->bow_02));
    assert(IsTextureValid(tm->bow_03));
    assert(IsTextureValid(tm->bow_04));
    assert(IsTextureValid(tm->bow_05));
    assert(IsTextureValid(tm->bow_06));
    assert(IsTextureValid(tm->bow_07));
    assert(IsTextureValid(tm->bow_08));
    assert(IsTextureValid(tm->bow_jump_00));
    assert(IsTextureValid(tm->bow_jump_01));
    assert(IsTextureValid(tm->bow_jump_02));
    assert(IsTextureValid(tm->bow_jump_03));
    assert(IsTextureValid(tm->bow_jump_04));
    assert(IsTextureValid(tm->bow_jump_05));
    assert(IsTextureValid(tm->cast_00));
    assert(IsTextureValid(tm->cast_01));
    assert(IsTextureValid(tm->cast_02));
    assert(IsTextureValid(tm->cast_03));
    assert(IsTextureValid(tm->cast_loop_00));
    assert(IsTextureValid(tm->cast_loop_01));
    assert(IsTextureValid(tm->cast_loop_02));
    assert(IsTextureValid(tm->cast_loop_03));
    assert(IsTextureValid(tm->corner_climb_00));
    assert(IsTextureValid(tm->corner_climb_01));
    assert(IsTextureValid(tm->corner_climb_02));
    assert(IsTextureValid(tm->corner_climb_03));
    assert(IsTextureValid(tm->corner_climb_04));
    assert(IsTextureValid(tm->corner_grab_00));
    assert(IsTextureValid(tm->corner_grab_01));
    assert(IsTextureValid(tm->corner_grab_02));
    assert(IsTextureValid(tm->corner_grab_03));
    assert(IsTextureValid(tm->corner_jump_00));
    assert(IsTextureValid(tm->corner_jump_01));
    assert(IsTextureValid(tm->crouch_00));
    assert(IsTextureValid(tm->crouch_01));
    assert(IsTextureValid(tm->crouch_02));
    assert(IsTextureValid(tm->crouch_03));
    assert(IsTextureValid(tm->crouch_walk_00));
    assert(IsTextureValid(tm->crouch_walk_01));
    assert(IsTextureValid(tm->crouch_walk_02));
    assert(IsTextureValid(tm->crouch_walk_03));
    assert(IsTextureValid(tm->crouch_walk_04));
    assert(IsTextureValid(tm->crouch_walk_05));
    assert(IsTextureValid(tm->die_00));
    assert(IsTextureValid(tm->die_01));
    assert(IsTextureValid(tm->die_02));
    assert(IsTextureValid(tm->die_03));
    assert(IsTextureValid(tm->die_04));
    assert(IsTextureValid(tm->die_05));
    assert(IsTextureValid(tm->die_06));
    assert(IsTextureValid(tm->drop_kick_00));
    assert(IsTextureValid(tm->drop_kick_01));
    assert(IsTextureValid(tm->drop_kick_02));
    assert(IsTextureValid(tm->drop_kick_03));
    assert(IsTextureValid(tm->fall_00));
    assert(IsTextureValid(tm->fall_01));
    assert(IsTextureValid(tm->get_up_00));
    assert(IsTextureValid(tm->get_up_01));
    assert(IsTextureValid(tm->get_up_02));
    assert(IsTextureValid(tm->get_up_03));
    assert(IsTextureValid(tm->get_up_04));
    assert(IsTextureValid(tm->get_up_05));
    assert(IsTextureValid(tm->get_up_06));
    assert(IsTextureValid(tm->hurt_00));
    assert(IsTextureValid(tm->hurt_01));
    assert(IsTextureValid(tm->hurt_02));
    assert(IsTextureValid(tm->idle_00));
    assert(IsTextureValid(tm->idle_01));
    assert(IsTextureValid(tm->idle_02));
    assert(IsTextureValid(tm->idle_03));
    assert(IsTextureValid(tm->idle2_00));
    assert(IsTextureValid(tm->idle2_01));
    assert(IsTextureValid(tm->idle2_02));
    assert(IsTextureValid(tm->idle2_03));
    assert(IsTextureValid(tm->items_00));
    assert(IsTextureValid(tm->items_01));
    assert(IsTextureValid(tm->items_02));
    assert(IsTextureValid(tm->jump_00));
    assert(IsTextureValid(tm->jump_01));
    assert(IsTextureValid(tm->jump_02));
    assert(IsTextureValid(tm->jump_03));
    assert(IsTextureValid(tm->kick_00));
    assert(IsTextureValid(tm->kick_01));
    assert(IsTextureValid(tm->kick_02));
    assert(IsTextureValid(tm->kick_03));
    assert(IsTextureValid(tm->kick_04));
    assert(IsTextureValid(tm->kick_05));
    assert(IsTextureValid(tm->kick_06));
    assert(IsTextureValid(tm->kick_07));
    assert(IsTextureValid(tm->knock_down_00));
    assert(IsTextureValid(tm->knock_down_01));
    assert(IsTextureValid(tm->knock_down_02));
    assert(IsTextureValid(tm->knock_down_03));
    assert(IsTextureValid(tm->knock_down_04));
    assert(IsTextureValid(tm->knock_down_05));
    assert(IsTextureValid(tm->knock_down_06));
    assert(IsTextureValid(tm->ladder_climb_00));
    assert(IsTextureValid(tm->ladder_climb_01));
    assert(IsTextureValid(tm->ladder_climb_02));
    assert(IsTextureValid(tm->ladder_climb_03));
    assert(IsTextureValid(tm->punch_00));
    assert(IsTextureValid(tm->punch_01));
    assert(IsTextureValid(tm->punch_02));
    assert(IsTextureValid(tm->punch_03));
    assert(IsTextureValid(tm->punch_04));
    assert(IsTextureValid(tm->punch_05));
    assert(IsTextureValid(tm->punch_06));
    assert(IsTextureValid(tm->punch_07));
    assert(IsTextureValid(tm->punch_08));
    assert(IsTextureValid(tm->punch_09));
    assert(IsTextureValid(tm->punch_10));
    assert(IsTextureValid(tm->punch_11));
    assert(IsTextureValid(tm->punch_12));
    assert(IsTextureValid(tm->run_00));
    assert(IsTextureValid(tm->run_01));
    assert(IsTextureValid(tm->run_02));
    assert(IsTextureValid(tm->run_03));
    assert(IsTextureValid(tm->run_04));
    assert(IsTextureValid(tm->run_05));
    assert(IsTextureValid(tm->run2_00));
    assert(IsTextureValid(tm->run2_01));
    assert(IsTextureValid(tm->run2_02));
    assert(IsTextureValid(tm->run2_03));
    assert(IsTextureValid(tm->run2_04));
    assert(IsTextureValid(tm->run2_05));
    assert(IsTextureValid(tm->run_punch_00));
    assert(IsTextureValid(tm->run_punch_01));
    assert(IsTextureValid(tm->run_punch_02));
    assert(IsTextureValid(tm->run_punch_03));
    assert(IsTextureValid(tm->run_punch_04));
    assert(IsTextureValid(tm->run_punch_05));
    assert(IsTextureValid(tm->run_punch_06));
    assert(IsTextureValid(tm->slide_00));
    assert(IsTextureValid(tm->slide_01));
    assert(IsTextureValid(tm->somersault_00));
    assert(IsTextureValid(tm->somersault_01));
    assert(IsTextureValid(tm->somersault_02));
    assert(IsTextureValid(tm->somersault_03));
    assert(IsTextureValid(tm->stand_00));
    assert(IsTextureValid(tm->stand_01));
    assert(IsTextureValid(tm->stand_02));
    assert(IsTextureValid(tm->sword_draw_00));
    assert(IsTextureValid(tm->sword_draw_01));
    assert(IsTextureValid(tm->sword_draw_02));
    assert(IsTextureValid(tm->sword_draw_03));
    assert(IsTextureValid(tm->sword_sheathe_00));
    assert(IsTextureValid(tm->sword_sheathe_01));
    assert(IsTextureValid(tm->sword_sheathe_02));
    assert(IsTextureValid(tm->sword_sheathe_03));
    assert(IsTextureValid(tm->walk_00));
    assert(IsTextureValid(tm->walk_01));
    assert(IsTextureValid(tm->walk_02));
    assert(IsTextureValid(tm->walk_03));
    assert(IsTextureValid(tm->walk_04));
    assert(IsTextureValid(tm->walk_05));
    assert(IsTextureValid(tm->wall_run_00));
    assert(IsTextureValid(tm->wall_run_01));
    assert(IsTextureValid(tm->wall_run_02));
    assert(IsTextureValid(tm->wall_run_03));
    assert(IsTextureValid(tm->wall_run_04));
    assert(IsTextureValid(tm->wall_run_05));
    assert(IsTextureValid(tm->wall_slide_00));
    assert(IsTextureValid(tm->wall_slide_01));
}

void texture_manager_shutdown(TextureManager *tm)
{
    assert(tm);

    UnloadTexture(tm->air_attack1_00);
    UnloadTexture(tm->air_attack1_01);
    UnloadTexture(tm->air_attack1_02);
    UnloadTexture(tm->air_attack1_03);
    UnloadTexture(tm->air_attack2_00);
    UnloadTexture(tm->air_attack2_01);
    UnloadTexture(tm->air_attack2_02);
    UnloadTexture(tm->air_attack_3_end_00);
    UnloadTexture(tm->air_attack_3_end_01);
    UnloadTexture(tm->air_attack_3_end_02);
    UnloadTexture(tm->air_attack3_loop_00);
    UnloadTexture(tm->air_attack3_loop_01);
    UnloadTexture(tm->air_attack3_ready_00);
    UnloadTexture(tm->attack1_00);
    UnloadTexture(tm->attack1_01);
    UnloadTexture(tm->attack1_02);
    UnloadTexture(tm->attack1_03);
    UnloadTexture(tm->attack1_04);
    UnloadTexture(tm->attack2_00);
    UnloadTexture(tm->attack2_01);
    UnloadTexture(tm->attack2_02);
    UnloadTexture(tm->attack2_03);
    UnloadTexture(tm->attack2_04);
    UnloadTexture(tm->attack2_05);
    UnloadTexture(tm->attack3_00);
    UnloadTexture(tm->attack3_01);
    UnloadTexture(tm->attack3_02);
    UnloadTexture(tm->attack3_03);
    UnloadTexture(tm->attack3_04);
    UnloadTexture(tm->attack3_05);
    UnloadTexture(tm->bow_00);
    UnloadTexture(tm->bow_01);
    UnloadTexture(tm->bow_02);
    UnloadTexture(tm->bow_03);
    UnloadTexture(tm->bow_04);
    UnloadTexture(tm->bow_05);
    UnloadTexture(tm->bow_06);
    UnloadTexture(tm->bow_07);
    UnloadTexture(tm->bow_08);
    UnloadTexture(tm->bow_jump_00);
    UnloadTexture(tm->bow_jump_01);
    UnloadTexture(tm->bow_jump_02);
    UnloadTexture(tm->bow_jump_03);
    UnloadTexture(tm->bow_jump_04);
    UnloadTexture(tm->bow_jump_05);
    UnloadTexture(tm->cast_00);
    UnloadTexture(tm->cast_01);
    UnloadTexture(tm->cast_02);
    UnloadTexture(tm->cast_03);
    UnloadTexture(tm->cast_loop_00);
    UnloadTexture(tm->cast_loop_01);
    UnloadTexture(tm->cast_loop_02);
    UnloadTexture(tm->cast_loop_03);
    UnloadTexture(tm->corner_climb_00);
    UnloadTexture(tm->corner_climb_01);
    UnloadTexture(tm->corner_climb_02);
    UnloadTexture(tm->corner_climb_03);
    UnloadTexture(tm->corner_climb_04);
    UnloadTexture(tm->corner_grab_00);
    UnloadTexture(tm->corner_grab_01);
    UnloadTexture(tm->corner_grab_02);
    UnloadTexture(tm->corner_grab_03);
    UnloadTexture(tm->corner_jump_00);
    UnloadTexture(tm->corner_jump_01);
    UnloadTexture(tm->crouch_00);
    UnloadTexture(tm->crouch_01);
    UnloadTexture(tm->crouch_02);
    UnloadTexture(tm->crouch_03);
    UnloadTexture(tm->crouch_walk_00);
    UnloadTexture(tm->crouch_walk_01);
    UnloadTexture(tm->crouch_walk_02);
    UnloadTexture(tm->crouch_walk_03);
    UnloadTexture(tm->crouch_walk_04);
    UnloadTexture(tm->crouch_walk_05);
    UnloadTexture(tm->die_00);
    UnloadTexture(tm->die_01);
    UnloadTexture(tm->die_02);
    UnloadTexture(tm->die_03);
    UnloadTexture(tm->die_04);
    UnloadTexture(tm->die_05);
    UnloadTexture(tm->die_06);
    UnloadTexture(tm->drop_kick_00);
    UnloadTexture(tm->drop_kick_01);
    UnloadTexture(tm->drop_kick_02);
    UnloadTexture(tm->drop_kick_03);
    UnloadTexture(tm->fall_00);
    UnloadTexture(tm->fall_01);
    UnloadTexture(tm->get_up_00);
    UnloadTexture(tm->get_up_01);
    UnloadTexture(tm->get_up_02);
    UnloadTexture(tm->get_up_03);
    UnloadTexture(tm->get_up_04);
    UnloadTexture(tm->get_up_05);
    UnloadTexture(tm->get_up_06);
    UnloadTexture(tm->hurt_00);
    UnloadTexture(tm->hurt_01);
    UnloadTexture(tm->hurt_02);
    UnloadTexture(tm->idle_00);
    UnloadTexture(tm->idle_01);
    UnloadTexture(tm->idle_02);
    UnloadTexture(tm->idle_03);
    UnloadTexture(tm->idle2_00);
    UnloadTexture(tm->idle2_01);
    UnloadTexture(tm->idle2_02);
    UnloadTexture(tm->idle2_03);
    UnloadTexture(tm->items_00);
    UnloadTexture(tm->items_01);
    UnloadTexture(tm->items_02);
    UnloadTexture(tm->jump_00);
    UnloadTexture(tm->jump_01);
    UnloadTexture(tm->jump_02);
    UnloadTexture(tm->jump_03);
    UnloadTexture(tm->kick_00);
    UnloadTexture(tm->kick_01);
    UnloadTexture(tm->kick_02);
    UnloadTexture(tm->kick_03);
    UnloadTexture(tm->kick_04);
    UnloadTexture(tm->kick_05);
    UnloadTexture(tm->kick_06);
    UnloadTexture(tm->kick_07);
    UnloadTexture(tm->knock_down_00);
    UnloadTexture(tm->knock_down_01);
    UnloadTexture(tm->knock_down_02);
    UnloadTexture(tm->knock_down_03);
    UnloadTexture(tm->knock_down_04);
    UnloadTexture(tm->knock_down_05);
    UnloadTexture(tm->knock_down_06);
    UnloadTexture(tm->ladder_climb_00);
    UnloadTexture(tm->ladder_climb_01);
    UnloadTexture(tm->ladder_climb_02);
    UnloadTexture(tm->ladder_climb_03);
    UnloadTexture(tm->punch_00);
    UnloadTexture(tm->punch_01);
    UnloadTexture(tm->punch_02);
    UnloadTexture(tm->punch_03);
    UnloadTexture(tm->punch_04);
    UnloadTexture(tm->punch_05);
    UnloadTexture(tm->punch_06);
    UnloadTexture(tm->punch_07);
    UnloadTexture(tm->punch_08);
    UnloadTexture(tm->punch_09);
    UnloadTexture(tm->punch_10);
    UnloadTexture(tm->punch_11);
    UnloadTexture(tm->punch_12);
    UnloadTexture(tm->run_00);
    UnloadTexture(tm->run_01);
    UnloadTexture(tm->run_02);
    UnloadTexture(tm->run_03);
    UnloadTexture(tm->run_04);
    UnloadTexture(tm->run_05);
    UnloadTexture(tm->run2_00);
    UnloadTexture(tm->run2_01);
    UnloadTexture(tm->run2_02);
    UnloadTexture(tm->run2_03);
    UnloadTexture(tm->run2_04);
    UnloadTexture(tm->run2_05);
    UnloadTexture(tm->run_punch_00);
    UnloadTexture(tm->run_punch_01);
    UnloadTexture(tm->run_punch_02);
    UnloadTexture(tm->run_punch_03);
    UnloadTexture(tm->run_punch_04);
    UnloadTexture(tm->run_punch_05);
    UnloadTexture(tm->run_punch_06);
    UnloadTexture(tm->slide_00);
    UnloadTexture(tm->slide_01);
    UnloadTexture(tm->somersault_00);
    UnloadTexture(tm->somersault_01);
    UnloadTexture(tm->somersault_02);
    UnloadTexture(tm->somersault_03);
    UnloadTexture(tm->stand_00);
    UnloadTexture(tm->stand_01);
    UnloadTexture(tm->stand_02);
    UnloadTexture(tm->sword_draw_00);
    UnloadTexture(tm->sword_draw_01);
    UnloadTexture(tm->sword_draw_02);
    UnloadTexture(tm->sword_draw_03);
    UnloadTexture(tm->sword_sheathe_00);
    UnloadTexture(tm->sword_sheathe_01);
    UnloadTexture(tm->sword_sheathe_02);
    UnloadTexture(tm->sword_sheathe_03);
    UnloadTexture(tm->walk_00);
    UnloadTexture(tm->walk_01);
    UnloadTexture(tm->walk_02);
    UnloadTexture(tm->walk_03);
    UnloadTexture(tm->walk_04);
    UnloadTexture(tm->walk_05);
    UnloadTexture(tm->wall_run_00);
    UnloadTexture(tm->wall_run_01);
    UnloadTexture(tm->wall_run_02);
    UnloadTexture(tm->wall_run_03);
    UnloadTexture(tm->wall_run_04);
    UnloadTexture(tm->wall_run_05);
    UnloadTexture(tm->wall_slide_00);
    UnloadTexture(tm->wall_slide_01);
}
